apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-server.fullname" . }}
  labels:
    {{- include "minecraft-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalIPs: {{ .Values.service.externalIPs }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "minecraft-server.selectorLabels" . | nindent 4 }}
